### Búsqueda con recarga automática
GET {{URL}}/products-search?q=monitor&category=Electrónica

### Sugerencias con precarga
GET {{URL}}/products-search/suggestions?q=sil

### HEALTH
GET {{URL}}/health-redis